"""Demo bootstrap - generates a self-contained scratch repo under
Demo/runtime/ (gitignored) so the UI can be explored with ZERO connection
to real repos. Run via Scripts/start_demo.bat.

The scratch repo uses a plain `.git` MARKER DIRECTORY (never a real git
repo, no git commands involved) - enough for the tracker to treat it as
online. Git status/commits fail gracefully (F41/F42), so the demo shows
everything except real commit History.
"""

import json
import shutil
from datetime import datetime, timedelta, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
RUNTIME = REPO_ROOT / "Demo" / "runtime"
DEMO_REPO = RUNTIME / "demo_repo"

DEMO_PLAN = """================================================================================
PLAN: v0.0.1.0  Demo plan - shows every attribution mode in the UI
================================================================================
This plan is DEMO DATA generated by Scripts/demo_bootstrap.py.
The duplicate task id and the absolute path below are INTENTIONAL - they
demonstrate the warnings banner.
================================================================================

<task id="A.1">
<title>Core engine (finished work)</title>
<status>done</status>
<files>
src/core/*.py
</files>
<why>Demo: a DONE task - its file events still attribute via MODE B.</why>
</task>

<task id="B.1">
<title>API layer (active work)</title>
<status>in-progress</status>
<files>
src/api/**
</files>
<why>Demo: the busy task - declared files hit MODE B, and it competes in
MODE A tie-breaks.</why>
</task>

<task id="C.1">
<title>Docs polish</title>
<status>pending</status>
<files>
docs/*.md
</files>
<why>Demo: overlaps with F.1 on docs -> AMBIGUOUS queue.</why>
</task>

<task id="D.1">
<title>Shared utils cleanup</title>
<status>pending</status>
<files>
shared/*.py
</files>
<why>Demo: shares files with in-progress E.1 -> MODE A scoped.</why>
</task>

<task id="E.1">
<title>Refactor sweep (active)</title>
<status>in-progress</status>
<files>
shared/*.py
D:/absolute/path/never_matches.py
</files>
<why>Demo: second in-progress task (so undeclared files go UNKNOWN, not
A-global) + an intentional absolute pattern for the warnings banner.</why>
</task>

<task id="F.1">
<title>Docs restructure</title>
<status>pending</status>
<files>
docs/*.md
</files>
<why>Demo: the other half of the docs AMBIGUOUS pair.</why>
</task>

<task id="F.1">
<title>INTENTIONAL duplicate id - triggers a warning</title>
<status>pending</status>
</task>

================================================================================
END OF PLAN
================================================================================
"""

# (file, tool, expected mode in the UI) - the recognizable mode showcase.
DEMO_EVENTS = [
    ("src/core/engine.py",    "Edit",  "B - tagged to done task A.1"),
    ("src/core/loader.py",    "Write", "B - A.1"),
    ("src/api/routes.py",     "Edit",  "B - B.1"),
    ("src/api/handlers/ws.py", "Edit", "B - B.1 (** glob)"),
    ("src/api/models.py",     "MultiEdit", "B - B.1"),
    ("shared/util.py",        "Edit",  "A_SCOPED - E.1 wins the D.1/E.1 tie"),
    ("shared/format.py",      "Write", "A_SCOPED - E.1"),
    ("docs/readme.md",        "Edit",  "AMBIGUOUS - C.1 vs F.1, pick manually!"),
    ("docs/changelog.md",     "Edit",  "AMBIGUOUS - C.1 vs F.1"),
    ("random/notes.txt",      "Write", "UNKNOWN - undeclared + 2 tasks in-progress, pick manually!"),
]

# File pool (repeats of the above, mode-preserving) used to spread synthetic
# activity across the last 14 days so the v0.1.3.0 Overview charts + status-bar
# sparkline have real shape (a single-day spike is a poor showcase).
_POOL = [(f, t) for f, t, _ in DEMO_EVENTS]


def _spread_events (now: datetime) -> list[tuple[str, str, str]]:
    """(ts, tool, file) rows spread over 14 days with a recent burst — feeds
    the activity line (14d), the sparkline (last 60min) and today's heartbeat.
    Deterministic (no RNG) so the demo is reproducible."""
    rows: list[tuple[str, str, str]] = []
    # a gently rising trend across the last 14 days (more edits recently)
    per_day = [1, 2, 1, 3, 2, 4, 3, 2, 5, 4, 3, 6, 4, 5]  # day-13 .. day-0
    for days_ago, count in zip(range(13, -1, -1), per_day):
        day = now - timedelta(days=days_ago)
        for k in range(count):
            f, t = _POOL[(days_ago * 7 + k) % len(_POOL)]
            ts = day.replace(hour=9 + (k % 8), minute=(k * 13) % 60, second=0,
                             microsecond=0)
            rows.append((ts.isoformat().replace("+00:00", "Z"), t, f))
    # a burst in the last ~50 minutes today -> lively sparkline + "just now"
    for i, (f, t, _) in enumerate(DEMO_EVENTS):
        ts = now - timedelta(minutes=50 - i * 5)
        rows.append((ts.isoformat().replace("+00:00", "Z"), t, f))
    rows.sort()  # events.jsonl is append-order = chronological
    return rows


def main () -> None:
    if RUNTIME.exists():
        try:
            shutil.rmtree(RUNTIME)
        except PermissionError:
            # CFT-15: demo.db is locked while a demo server is running -
            # a raw traceback here violates the KATLAB clear-abort BAT
            # convention (F54-class).
            print("[ABORT] Demo/runtime is locked - a demo server is still "
                  "running. Close its console window (or stop it) and retry.")
            raise SystemExit(1)
    (DEMO_REPO / ".git").mkdir(parents=True)           # marker only - NOT a git repo
    plans = DEMO_REPO / "temp" / "Plan"
    plans.mkdir(parents=True)
    (plans / "PLAN_v0.0.1.0_Demo.txt").write_text(DEMO_PLAN, encoding="utf-8")

    tracking = DEMO_REPO / ".katlab_tracking"
    tracking.mkdir()
    # v0.1.3.0: spread events over 14 days + a recent burst so the Overview
    # dashboard (14d activity line, mode doughnut, per-task bar) and the
    # status-bar sparkline (last 60min) have real shape to show.
    spread = _spread_events(datetime.now(timezone.utc))
    with open(tracking / "events.jsonl", "w", encoding="utf-8") as handle:
        for ts, tool, file in spread:
            handle.write(json.dumps(
                {"v": 1, "ts": ts, "tool": tool, "file": file}) + "\n")

    # CFT-13: port 8101 - the demo must coexist with a real tracker on 8100.
    config = RUNTIME / "repos.demo.yaml"
    config.write_text(
        "server:\n  host: 127.0.0.1\n  port: 8101\n  status_poll_seconds: 30\n"
        "repos:\n"
        "  - id: Demo\n"
        "    name: \"Demo scratch repo (generated)\"\n"
        f"    path: '{DEMO_REPO}'\n"
        "    plan_globs:\n"
        "      - \"temp/Plan/PLAN_*.txt\"\n",
        encoding="utf-8",
    )

    print(f"Demo generated at {RUNTIME}")
    print("Mode showcase (Changes view + Overview doughnut):")
    for file, _tool, expected in DEMO_EVENTS:
        print(f"  {file:26s} -> {expected}")
    print("  + 2 warnings in the banner (duplicate id, absolute pattern)")
    print("v0.1.3.0 visuals: Overview tab (doughnut/bar/14d line), status-bar")
    print("  sparkline (recent burst), Relationship map (task -> uncommitted).")


if __name__ == "__main__":
    main()
